"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { Columns3, ExternalLink, Pencil, Search, Trash2 } from "lucide-react";
import { deleteDailyTaskAction } from "@/app/(app)/tareas-diarias/actions";
import { Badge } from "@/components/ui/badge";
import { DAILY_STATUS_LABELS, SOURCE_LABELS } from "@/lib/constants";
import type { AppRole, DailyTask, TeamMember } from "@/lib/types";
import { canEdit, formatDate, formatDateTime, formatHours } from "@/lib/utils";

type Column = "date"|"client"|"description"|"hours"|"status"|"work"|"source"|"ticket"|"url"|"comments"|"updated"|"actions";
const definitions: Array<{key:Column;label:string;visible:boolean}> = [
  {key:"date",label:"Fecha",visible:true},{key:"client",label:"Cliente",visible:true},{key:"description",label:"Tarea",visible:true},{key:"hours",label:"HH",visible:true},{key:"status",label:"Estado",visible:true},{key:"work",label:"Trabajo principal",visible:true},{key:"source",label:"Origen",visible:false},{key:"ticket",label:"Ticket / ID",visible:false},{key:"url",label:"Enlace",visible:false},{key:"comments",label:"Comentarios",visible:false},{key:"updated",label:"Actualización",visible:false},{key:"actions",label:"Acciones",visible:true},
];
function defaults(){ return Object.fromEntries(definitions.map(c=>[c.key,c.visible])) as Record<Column,boolean>; }

export function DailyTasksTable({ tasks, role, member, onEdit }: { tasks: DailyTask[]; role: AppRole; member: TeamMember; onEdit:(task:DailyTask)=>void }) {
  const storageKey=`tbx-daily-columns-${member.id}`;
  const [search,setSearch]=useState(""); const [status,setStatus]=useState("all"); const [association,setAssociation]=useState("all");
  const [from,setFrom]=useState(""); const [to,setTo]=useState(""); const [menu,setMenu]=useState(false); const ref=useRef<HTMLDivElement>(null);
  const [visible,setVisible]=useState<Record<Column,boolean>>(()=>{ if(typeof window==="undefined") return defaults(); try{return {...defaults(),...JSON.parse(localStorage.getItem(storageKey)??"{}")};}catch{return defaults();}});
  useEffect(()=>localStorage.setItem(storageKey,JSON.stringify(visible)),[visible,storageKey]);
  useEffect(()=>{const close=(e:MouseEvent)=>{if(ref.current&&!ref.current.contains(e.target as Node))setMenu(false)};document.addEventListener("mousedown",close);return()=>document.removeEventListener("mousedown",close)},[]);
  const filtered=useMemo(()=>tasks.filter(t=>{const q=search.toLowerCase().trim();return(!q||[t.client_name,t.description,t.source_reference,t.comments,t.work_item?.title].filter(Boolean).join(" ").toLowerCase().includes(q))&&(status==="all"||t.status===status)&&(association==="all"||(association==="linked")===Boolean(t.work_item_id))&&(!from||t.task_date>=from)&&(!to||t.task_date<=to)}),[tasks,search,status,association,from,to]);
  const hours=filtered.reduce((sum,t)=>sum+t.hours,0);
  return <div>
    <div className="mb-4 grid gap-2 lg:grid-cols-[minmax(220px,1fr)_150px_160px_150px_150px_auto]"><label className="relative"><Search className="absolute left-3 top-3" size={17}/><input className="tbx-input pl-10" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar tarea, cliente o ticket…"/></label><select className="tbx-input" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">Todos los estados</option>{Object.entries(DAILY_STATUS_LABELS).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><select className="tbx-input" value={association} onChange={e=>setAssociation(e.target.value)}><option value="all">Todas</option><option value="linked">Asociadas</option><option value="unlinked">Sin asociar</option></select><input className="tbx-input" type="date" value={from} onChange={e=>setFrom(e.target.value)}/><input className="tbx-input" type="date" value={to} onChange={e=>setTo(e.target.value)}/><div className="relative" ref={ref}><button className="tbx-button-secondary w-full" onClick={()=>setMenu(!menu)}><Columns3 size={17}/> Columnas</button>{menu?<div className="absolute right-0 top-12 z-20 w-60 rounded-xl border border-[var(--tbx-border)] bg-[var(--tbx-surface)] p-3 shadow-xl">{definitions.map(c=><label key={c.key} className="flex cursor-pointer items-center gap-3 rounded-lg px-2 py-2 hover:bg-[var(--tbx-surface-2)]"><input type="checkbox" checked={visible[c.key]} onChange={()=>setVisible(v=>({...v,[c.key]:!v[c.key]}))}/><span className="text-sm">{c.label}</span></label>)}<button className="tbx-button-ghost mt-2 w-full" onClick={()=>setVisible(defaults())}>Restablecer</button></div>:null}</div></div>
    <div className="mb-3 flex justify-between text-sm"><span>{filtered.length} registros · <strong className="text-[var(--tbx-text)]">{formatHours(hours)} HH</strong></span><span className="tbx-mono text-[.68rem] uppercase tracking-[.1em]">columnas guardadas por pestaña</span></div>
    <div className="tbx-table-scroll"><table className="tbx-table"><thead><tr>{visible.date&&<th>Fecha</th>}{visible.client&&<th>Cliente</th>}{visible.description&&<th>Tarea</th>}{visible.hours&&<th>HH</th>}{visible.status&&<th>Estado</th>}{visible.work&&<th>Trabajo principal</th>}{visible.source&&<th>Origen</th>}{visible.ticket&&<th>Ticket / ID</th>}{visible.url&&<th>Enlace</th>}{visible.comments&&<th>Comentarios</th>}{visible.updated&&<th>Actualización</th>}{visible.actions&&<th>Acciones</th>}</tr></thead><tbody>{filtered.map(t=><tr key={t.id} className="cursor-pointer" onClick={e=>{if(!(e.target as HTMLElement).closest("button,a,form,input"))onEdit(t)}}>{visible.date&&<td className="whitespace-nowrap">{formatDate(t.task_date)}</td>}{visible.client&&<td className="font-semibold text-[var(--tbx-text)]">{t.client_name}</td>}{visible.description&&<td className="min-w-72"><strong className="text-[var(--tbx-text)]">{t.description}</strong></td>}{visible.hours&&<td className="tbx-mono font-semibold">{formatHours(t.hours)}</td>}{visible.status&&<td><Badge tone={t.status==="done"?"green":t.status==="blocked"?"red":"amber"}>{DAILY_STATUS_LABELS[t.status]}</Badge></td>}{visible.work&&<td className="min-w-64">{t.work_item?<><span className="tbx-mono text-xs">{t.work_item.code}</span><p>{t.work_item.title}</p></>:<Badge tone="amber">Sin asociar</Badge>}</td>}{visible.source&&<td>{SOURCE_LABELS[t.source]}</td>}{visible.ticket&&<td className="tbx-mono text-xs">{t.source_reference||"—"}</td>}{visible.url&&<td>{t.source_url?<a href={t.source_url} target="_blank" rel="noreferrer" className="inline-flex gap-1 text-[var(--tbx-support)]">Abrir <ExternalLink size={13}/></a>:"—"}</td>}{visible.comments&&<td className="min-w-60">{t.comments||"—"}</td>}{visible.updated&&<td className="whitespace-nowrap text-xs">{formatDateTime(t.updated_at)}</td>}{visible.actions&&<td><div className="flex gap-1"><button className="tbx-button-ghost" onClick={()=>onEdit(t)}><Pencil size={16}/></button>{canEdit(role)?<form action={deleteDailyTaskAction} onSubmit={e=>{if(!confirm("¿Eliminar esta tarea diaria?"))e.preventDefault()}}><input type="hidden" name="id" value={t.id}/><button className="tbx-button-ghost text-[var(--tbx-danger)]"><Trash2 size={16}/></button></form>:null}</div></td>}</tr>)}{!filtered.length?<tr><td colSpan={12} className="py-12 text-center">No hay tareas para estos filtros.</td></tr>:null}</tbody></table></div>
  </div>;
}
